### ISSUE TITLE
NodeSchool - 4th July

### ISSUE THREAD

**Issue by avin45h** [nodeschool/Delhi-NCR#11]
All Discussions here.

What we have decided so far -

To The New Digital is providing space and sponsorship for the event.
The event will be held on 4th July.
@VibhorKukreja and @manoj-nama  are the point of contact for us collaborators and To The New Digital.

**Comment by kushal-likhi** [comment]
Awesome,, Count me in :)

**Comment by manoj-nama** [comment]
Learning from the last **NodeSchool** *event*, we have decided to change the track of the event on `4th July 2015`.

We will be having *two* workshops from `nodeschool.io`, one before lunch and one after.

Before each of the workshops, we have decided we will have a session for any of the latest and hot topics / technology in our *domain*. 

The proposed agenda / day will look like:
* *Session* (ex. Ionic)
* `nodeschool.io` workshop
* **Lunch**
* *Session* (ideally someone from community should own this, owners welcome)
* `nodeschool.io` workshop
* Windup

@kushal-likhi, @avin45h  you up for owning a session *for the community*? ;)

The place will be `4th floor, Tower B, Logix Technopark. Sector 127 Noida` (*opposite HCL*) on `4th July 2015`
We'll be having food and drinks.

Subscribe here for updates!! 

(*Keep being async*)

**Comment by avinash-jabong** [comment]
Ionic will be an overkill in my opinion. It itself is a huge discussion topic for the whole day.

**Comment by avinash-jabong** [comment]
How about we take some two advanced nodeschool.io tasks and then present with the best of the knowledge? I still see people abusing closures, chains, promises, delete operators ...

**Comment by manoj-nama** [comment]
@avinash-jabong @avin45h ionic was just an example, it is not happening as it is too broad

**Comment by avinash-jabong** [comment]
cool :) I thought it was something like ionic. Yup, the plan looks good then.

**Comment by kushal-likhi** [comment]
We can talk about iojs ;) and its added features. Or stream based programming in node, or Hapi ;)

**Comment by manoj-nama** [comment]
@kushal-likhi choose one! which one would you like to own ;)

**Comment by manoj-nama** [comment]
*Register yourself* @ [Nodeschool Delhi-NCR chapter](http://nodeschool.io/Delhi-NCR/)

**IT'S FREE!!**

**Comment by avinash-jabong** [comment]
@manoj-nama  What workshops have been finalized?

**Comment by manoj-nama** [comment]
Hi *all*,

The day will progress as follows:

1. We'll be having a session on `nodejs streams` by @kushal-likhi 
2. We will be having two `nodeschool.io` *workshops* in **parallel**  
    *  `learnyounode` (for people who are a bit new / raw with `nodejs`)
    *  `stream-adventure` for the rest of attendees
3. We'll break for lunch at 02:00PM
4. Session on `hapijs` by @kashishgupta1990 and @deepakshrma
5. Common workshop `make-me-hapi`
6. Windup and feedback

**Comment by kashishgupta1990** [comment]
Hello Guys,

Finally the day we were waiting for anxiously has arrived, Only one day to go for NodeSchool Delhi-NCR 2015

Below are the complete details / agenda:

Agenda
1.1. We’ll be having a shuttle from botanical garden metro station @09:00AM Sharp (Please be on time to avail the facility)
*1.2*. *9:30 AM* - Tea and snacks
*1.3*. *09:50 AM* - Keynote by *Shweta Sharma*
*1.3*. *10:00 AM* - Presentation by *Kushal Likhi* on node streams
*1.4*. *11:30 AM* - Nodeschool workshops hands-on (learnyounode and stream-adventure)
*1.5*. *01:30 - 02:30 PM* - Lunch
*1.6*. *02:30 PM* - Presentation by *Kashish Gupta* and *Deepak Vishwakarma* on hapi js
*1.7*. *4:00 PM* - Nodeschool workshop hands-on (make-me-hapi)
*1.8*. *5:30 - 06:00* - Post event huddle / open discussion
*1.9*. *06:00 PM* - Shuttle from *TO THE NEW Digital* office to Botanical garden metro station
Important note

Attendees are required to bring-along their own machines
Nodejs must be installed prior to starting any of the sessions/workshops
VENUE: 4th floor, Tower-B, Logix Technopark Sector-127 Noida (Opp HCL) - 201305
Point of contact - Manoj Nama (+91-9911557793), Vibhor Kukreja (+91-9873512530), Kashish Gupta (+91-9999749722)
Hope to see you there tomorrow

**Comment by manoj-nama** [comment]
For those who would be availing the shuttle service from *Botanical Garden Metro Station*, 
Bus no is : **UP-16 CT 1763**

It would depart @`09:00 AM`
