### ISSUE TITLE
Requesting Membership

### ISSUE THREAD

**Issue by vineetdaniel** [nodeschool/Delhi-NCR#6]
Hi, I would like to join nodeschool chapter for Delhi-NCR. I am @vineetdaniel on twitter and work as a Consultant in the field of scalability, automation, database etc. You can visit my linked in profile http://in.linkedin.com/in/vineetdaniel . I have been using Node.js for quite some time now.

**Comment by kushal-likhi** [comment]
@vineetdaniel Hi! Please checkout Issue #8 for our next event on `28 Feb, 15`. Please feel free to discuss there. :)

Closing this as #8 will take it forward.
