### ISSUE TITLE
Plan the Feb NodeSchool event.

### ISSUE THREAD

**Issue by kushal-likhi** [nodeschool/Delhi-NCR#7]
Lets plan it here, like this everyone will be informed. If this works we can use github issues to plan upcoming events too.. :+1:

**Comment by avin45h** [comment]
decide location! we need wifi too

**Comment by kashishgupta1990** [comment]
cafe coffee day can be the place or any thing similar

**Comment by avin45h** [comment]
won't work, wifi issues. Here is what we need to address according to me
1. location
2. tasks for experienced people
3. a session or a presentation, most preferably a business case of node.js and it's implementation

The main problem with last nodeschool was the difficulty level. The people who came in were experienced and found tasks too boring in second half. We need to add something that adds up to their knowledge.

**Comment by DishankJindal** [comment]
I am a student. I am not a professional But, interested in learning node.js. Can i attend the workshop?

**Comment by avin45h** [comment]
It will be open to all, we are trying to find out a location for that, the
office space isnt available for a while as we just shifted. @Kushal, any
place suggestions????



*AVINASH VERMA*

Senior Software Engineer

T : +91 1206493668                           M : +91 9953 737 236

E : avinash@intelligrape.com                   W : www.intelligrape.com

[image: Description: Description: Intelligrape_Signature Temp]

**Comment by DishankJindal** [comment]
When will your are going to host ? And what are prerequisites for the seminar? 
I know html, css and basic java script.

**Comment by avin45h** [comment]
we are working out on getting it hosted at the earliest. The prerequisites
are not much, just a familiarity with object oriented javascript should do.



*AVINASH VERMA*

Senior Software Engineer

T : +91 1206493668                           M : +91 9953 737 236

E : avinash@intelligrape.com                   W : www.intelligrape.com

[image: Description: Description: Intelligrape_Signature Temp]

**Comment by kushal-likhi** [comment]
Hey! Yes we can do it in Okhla, lets plan any weekend.

**Comment by suroorwijdan** [comment]
Lets plan it out and do it at 91springboard located at Okhla, will be reachable for most people around Delhi/NCR. We should fix a date and discuss on the overall agenda and topics.

**Comment by avin45h** [comment]
Let's have a discussion this weekend.



*AVINASH VERMA*

Senior Software Engineer

T : +91 1206493668                           M : +91 9953 737 236

E : avinash@intelligrape.com                   W : www.intelligrape.com

[image: Description: Description: Intelligrape_Signature Temp]

**Comment by DishankJindal** [comment]
Is the location and date is final?

**Comment by avin45h** [comment]
Not yet, give us this weekend. We will come up with a venue and date.



*AVINASH VERMA*

Senior Software Engineer

T : +91 1206493668                           M : +91 9953 737 236

E : avinash@intelligrape.com                   W : www.intelligrape.com

[image: Description: Description: Intelligrape_Signature Temp]

**Comment by DishankJindal** [comment]
In the seminar what are topics you will cover up? Basic type or some
serious tbin

**Comment by avin45h** [comment]
Dishank, we really appreciate your interest in this. But please give us this weekend to plan out the next nodeschool. We all are working people in different places, and it needs some time to gather at a place to discuss about organizing any community event. We will really appreciate if you give us some time so that we can answer your queries.

**Comment by DishankJindal** [comment]
Definitely sir. I just want you to know, i shall be comming from Chandigarh.
On Feb 13, 2015 9:50 PM, "Avinash Verma" <notifications@github.com> wrote:
>
> Dishank, we really appreciate your interest in this. But please give us
this weekend to plan out the next nodeschool. We all are working people in
different places, and it needs some time to gather at a place to discuss
about organizing any community event. We will really appreciate if you give
us some time so that we can answer your queries.

**Comment by kushal-likhi** [comment]
Closing this as Issue #8 will take it forward.

**Comment by DishankJindal** [comment]
Please provide me full address of the location and contact details.

**Comment by DishankJindal** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Dishank

Confirm that you know Dishank: https://www.linkedin.com/e/v2?e=-9599ky-ic2y8aq3-5u&amp;t=ssuw&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=0lwMlRCZ&amp;invitationId=6026605683502260226


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-9599ky-ic2y8aq3-5u&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQF-5BnIZ_IgkgAAAU6LN9dXUW78sqHiJSFHBy5XFIMJaW8XY84SfQfWusrxydtRWlbyj5SHPgrkLnkcufh4jEp47gO6tKp0FMbIsgDmtyHZukOfrhshWLfj5y_N8oS7BOpGqVtPmSTYmy_rLBM2KuW3mOiZTnsXLZWTgw7xeRDTRPy7Ek_QyMrjlBTk9iUy3zYc&amp;eid=-9599ky-ic2y8aq3-5u Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-9599ky-ic2y8aq3-5u&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by DishankJindal** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Dishank

Confirm that you know Dishank: https://www.linkedin.com/e/v2?e=-u4461v-ic2y8aqe-43&amp;t=ssuw&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=FajSDkwr&amp;invitationId=6026605683305119745


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-u4461v-ic2y8aqe-43&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQGnWdn_p2hiIwAAAU6LN9mLFe0vOi1_RXgdkf3kHpdbcuqTnAkJEnAFu8C5gAgQVdOm6CnUzeLHOuUDUdIPCo__10G2pAUtDEP5n1qayKDkNfBltFDJjcK_Ya5uRr4sA1VD-g4HhjdKiVJcK7rbwAjDv8n8WQYh5-9qGF0sjf3YHU7StNQd5t2ILyJsp148zBxZ&amp;eid=-u4461v-ic2y8aqe-43 Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-u4461v-ic2y8aqe-43&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by DishankJindal** [comment]
Dishank Jindal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Rd3sVcj4Rc3cPe3oRc3oScz0Sfkh9rCZFt65QqnpKqipOtSJ4kSFxhzRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4Cp3kJcC4QdCVyoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=

View Dishank Jindal&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3oMd34VdPwNcPR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCtD1KfngCp3kJcC4QdCVyoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jkNpm5BcPcMpmcVdz5xczATcjpBdmoMcj4Mc30Mc30MpCcOejxzdm4SpC4RdCoRdj5CpjkTc3cTe68Rd39Bp35BdztAc3dCdjkTdCdxe3kQc3oMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zkQdPANcjkMcPcUdzkMdzoOc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCp3kJcC4QdCVyoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1AdiQOojgSrC9zqiRScjoQd7kJfmhFpip3u5hInQROgm53mCRqt4p6qkNIujhNsk5gh3B2dRkNcmJOq6FagDBUkmFPp6ZHtmJfsDd6h5h9i45xp3tzcD59q55PqCpQsAtmiAoTdjdUmAJylCNKjBlmejB3cQ4MuCMPd4NmiAFvjCtqcAVFqDthbn5fqD9Cr5BgjmFLh5ETc6dcuk5GtANmlT1RhnxloTdFkSAMqAQRrQhWsndksn5dq4Byp3lkjnhRqkJTgClWqD8Slk51gk5Rm5dFtndorT53i551fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCp3kJcC4QdCVyoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6026605701055422464_500&amp;markAsRead=This email was intended for nodeschool/Delhi-NCR. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cp3kJcC4QdCVyoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by DishankJindal** [comment]
Dishank Jindal would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Rd3sVcj4Rc3cPe3oRc3oScz0Sfkh9rCZFt65QqnpKqipOtSJ4kSFxhzRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9z8JtShVqSlIoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=

View Dishank Jindal&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3oMd34VdPwNcPR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DpMrzRQ9z8JtShVqSlIoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBdj5BomkPcP1BoPAScm4OejsNdCkRpz0Ncj0Mc30Mc31CoP8Ve6cRojpCojkSpzkRcmpBdjsMcPsUozkQcClAcmkSdSgMcSoRdjsSoS4UdjgMdz0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACdjgTej4Ndj0PcPwSdj0Sdz8MdzRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9z8JtShVqSlIoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=cyRTp7BHpmNzqiRScjoQd7kJfmhFpipip4F9tjdekkFmmCtaukteq70TgAxdmnlNsztis5ZhnP1Tr7hjkStnsRBMsQBhdRYVoCBLd4lhhAJkhBdotCJOgnASi6JapSJ3qAV4kQJPgmdOmAdeknlLjAtnnQ9dsQN9cAlconsVj7dCunxgpBlBjjBghkdHdnF1t3d8dl4QcjdedQZvrQNnoTBmp31EqABVrjt3pzdfqnlhe7ljhT9fenhMm7hMoCkMl6VojmFPtAYTlk51gk5lgQkRjAR5jmNni551fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9z8JtShVqSlIoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6026605701055422464_500&amp;markAsRead=This email was intended for nodeschool/Delhi-NCR. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9z8JtShVqSlIoSAJtz4Sd3hRbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6026605701055422464_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
