### ISSUE TITLE
Plan Event on 28 Feb

### ISSUE THREAD

**Issue by kushal-likhi** [nodeschool/Delhi-NCR#8]
We have the space, and Innox & moodyfi.com will sponsor beer, drinks and snacks.. ;)

@Team lets make it happen. Discuss here!!!!

**Comment by DishankJindal** [comment]
Please provide me full address of the location and contact details.

**Comment by avin45h** [comment]
@kushal-likhi  What are the final plans as of now?

**Comment by avin45h** [comment]
@kushal-likhi , refer to #12 , closing this one
