### ISSUE TITLE
How can I register as a mentor in the event?

### ISSUE THREAD

**Issue by Faiz7412** [nodeschool/Delhi-NCR#9]

**Comment by avin45h** [comment]
You can, Just keep a track of activities here. And whenever we plan an event, join in. There will be an event soon in a month or two (Right now dealing with a job change). I can add you to the repository as well, but I need to know a little more about your skills :). I hope that is okay.

**Comment by Faiz7412** [comment]
You can view my github repositories to see some of my works.
My linkedIn: https://www.linkedin.com/in/faiz95
Here's my website: http://faiz.io
I am fluent with javascript and working in greymeter. I'm conducting a hackathon sponsored by Unicommerce. 
Also, i have plans to launch a startup by the end of next month. 
Looking forward to hear from you.

**Comment by VibhorKukreja** [comment]
Hi Faiz, 
We are planning for this on 4th July, 2015 for our next NodeSchool-MeetUp. We will update you soon regarding it.

**Comment by avin45h** [comment]
@VibhorKukreja  at IG? Let's have an organisation independent one, I am planning to get some other guys as mentors as well.

**Comment by avin45h** [comment]
@Faiz7412 Refer to #11 and join us. We would really love your participation.
